services:
  - type: web
    name: room4work-backend
    env: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT src.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: room4work-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
  - type: web
    name: room4work-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./build"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

databases:
  - name: room4work-db
    databaseName: room4work
    user: room4work_user

